image: docker:latest

services:
  - docker:dind

stages:
  - deploy

deploy_virtual:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "virtual"'   # Только ветка virtual
  script:
    - docker info
    - docker-compose --version
    - docker-compose down || true
    - docker-compose up -d --build
