stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Docker
build-job:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

test-job:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run --rm fastapi pytest

deploy:
  stage: deploy
  script:
    - docker-compose up -d'
