version: "3.9"

networks:
  dev:
  
volumes:
  nginx-conf: {}

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - nextjs
      - fastapi
    networks:
      - dev

  nextjs:
    build: ./bolzhau.ai-main
    container_name: nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - dev

  fastapi:
    build: ./backend
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    networks:
      - dev
