version: "3.9"

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "2422:80"
      - "2423:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./bolzhau.ai-main/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - bolzhau.ai-main
    networks:
      - dev

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - dev

  bolzhau.ai-main:
    build:
      context: ./bolzhau.ai-main
    container_name: bolzhau_ai
    ports:
      - "3000:3000"
    networks:
      - dev
